Log4j Configuration
MunifNagi/Solvd-AirPort pull request #3
Opened 2022-08-10 02:19 UTC by MunifNagi

Adding logger

2022-08-12 13:08 UTC, VbKoshak requested changes

2022-08-12 13:08 UTC, VbKoshak commented on src/classes/Employee.java
> +        if (chosen>flights.size()){return  null;}
either 
```
if (chosen > flights.size()) {
...
}
```
or 
```
if (chosen > flights.size()) return null;
```
But the first one is more preferable

2022-08-12 13:08 UTC, VbKoshak commented on src/classes/Main.java
> +        if (chosen==null){logger.warn("No Flight has been chosen");}
format here

2022-08-12 13:08 UTC, VbKoshak commented on src/classes/Main.java
this empty line is not necessary

2022-08-22 11:04 UTC, VbKoshak approved these changes
lgtm

2022-08-22 20:14 UTC, MunifNagi commented
outdated pull request

2022-08-22 20:14 UTC, closed without merging